# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/': null
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:5173', 'https://nationsoundfull.pixelevent.site']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        expose_headers: []
        max_age: 3600
    paths:
        '^/': # Cela applique les règles CORS à toutes les routes. Vous pouvez spécifier des chemins spécifiques si nécessaire.
            allow_origin: ['http://localhost:5173', 'https://nationsoundfull.pixelevent.site']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            max_age: 3600