security:
    password_hashers:
        App\Entity\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost:      15
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        webuser_userprovider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        login:
            pattern: ^/webuser/login
            provider: webuser_userprovider
            stateless: true
            json_login:
                check_path: /webuser/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern:   ^/webuser
            provider: webuser_userprovider
            stateless: true
            jwt: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
   
    access_control:
        - { path: ^/webuser/register, roles: PUBLIC_ACCESS  }
        - { path: ^/webuser/login, roles: PUBLIC_ACCESS  }
        - { path: ^/webuser,       roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER